server:
  port: 8081

ibm:
  mq:
    queueManager: QM1
    channel: DEV.APP.SVRCONN
    connName: localhost(1414)
    user: app
    password: passw0rd
    ssl-cipher-spec: TLS_AES_256_GCM_SHA384
    use-i-b-m-cipher-mappings: false
    ssl-bundle: ibm-mq

spring:
  ssl:
    bundle:
      jks:
        ibm-mq:
          keystore:
            location: ${KEYSTORE_PATH}
            password: ${KEYSTORE_PASSWORD}
            type: "PKCS12"
          truststore:
            location: ${TRUSTSTORE_PATH}
            password: ${TRUSTSTORE_PASSWORD}
            type: "PKCS12"
